import './globals.css'
import { Inter } from 'next/font/google'
import Providers from '@/redux/provider'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'GoTrip',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <Providers>
        <body className={inter.className}>{children}</body>
      </Providers>
    </html>
  )
}
